(deftheme hrbsd
  "Created 2019-10-19.")

(custom-theme-set-faces
 'hrbsd
 '(default ((t (:family "Menlo" :foundry "nil" :width normal :height 150 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#ebebeb" :background "#2a525b" :stipple nil :inherit nil))))
 '(cursor ((((class color) (min-colors 16777215)) (:background "#fdf4c1")) (((class color) (min-colors 255)) (:background "#ffffaf"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((class color) (min-colors 16777215)) (:foreground "#8ec07c")) (((class color) (min-colors 255)) (:foreground "#87af87"))))
 '(homoglyph ((((class color) (min-colors 16777215)) (:foreground "#fabd2f")) (((class color) (min-colors 255)) (:foreground "#ffaf00"))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#b8bb26" :background "#1d2021"))))
 '(highlight ((((class color) (min-colors 16777215)) (:foreground "#fdf4c1" :background "#7c6f64")) (((class color) (min-colors 255)) (:foreground "#ffffaf" :background "#767676"))))
 '(region ((((class color) (min-colors 16777215)) (:background "#2a525b")) (((class color) (min-colors 255)) (:background "#2a525b"))))
 '(shadow ((((class color) (min-colors 16777215)) (:foreground "#7c6f64")) (((class color) (min-colors 255)) (:foreground "#767676"))))
 '(secondary-selection ((((class color) (min-colors 16777215)) (:background "#3c3836")) (((class color) (min-colors 255)) (:background "#3a3a3a"))))
 '(trailing-whitespace ((((class color) (min-colors 16777215)) (:background "#fb4933")) (((class color) (min-colors 255)) (:background "#d75f5f"))))
 '(font-lock-builtin-face ((((class color) (min-colors 16777215)) (:foreground "#fe8019")) (((class color) (min-colors 255)) (:foreground "#ff8700"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((((class color) (min-colors 16777215)) (:foreground "#7c6f64")) (((class color) (min-colors 255)) (:foreground "#767676"))))
 '(font-lock-constant-face ((((class color) (min-colors 16777215)) (:foreground "#d3869b")) (((class color) (min-colors 255)) (:foreground "#d787af"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((((class color) (min-colors 16777215)) (:foreground "#fabd2f")) (((class color) (min-colors 255)) (:foreground "#ffaf00"))))
 '(font-lock-keyword-face ((((class color) (min-colors 16777215)) (:foreground "#fb4933")) (((class color) (min-colors 255)) (:foreground "#d75f5f"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((((class color) (min-colors 16777215)) (:foreground "#b8bb26")) (((class color) (min-colors 255)) (:foreground "#afaf00"))))
 '(font-lock-type-face ((((class color) (min-colors 16777215)) (:foreground "#d3869b")) (((class color) (min-colors 255)) (:foreground "#d787af"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 16777215)) (:foreground "#83a598")) (((class color) (min-colors 255)) (:foreground "#87afaf"))))
 '(font-lock-warning-face ((((class color) (min-colors 16777215)) (:bold t :foreground "#fb4933")) (((class color) (min-colors 255)) (:bold t :foreground "#d75f5f"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line) :foreground "#458588"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:background "#1d2021"))))
 '(header-line ((((class color) (min-colors 16777215)) (:inherit nil :box nil :foreground "#bdae93" :background "#282828")) (((class color) (min-colors 255)) (:inherit nil :box nil :foreground "#a8a8a8" :background "#262626"))))
 '(tooltip ((((class color) (min-colors 16777215)) (:background "#3c3836" :foreground "#ebdbb2")) (((class color) (min-colors 255)) (:background "#3a3a3a" :foreground "#ffdfaf"))))
 '(mode-line ((((class color) (min-colors 16777215)) (:box nil :foreground "#d5c4a1" :background "#665c54")) (((class color) (min-colors 255)) (:box nil :foreground "#bcbcbc" :background "#626262"))))
 '(mode-line-buffer-id ((t (:weight bold))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((((class color) (min-colors 16777215)) (:box nil :foreground "#a89984" :background "#3c3836")) (((class color) (min-colors 255)) (:box nil :foreground "#949494" :background "#3a3a3a"))))
 '(isearch ((((class color) (min-colors 16777215)) (:background "#fe8019" :foreground "#000000")) (((class color) (min-colors 255)) (:background "#ff8700" :foreground "#000000"))))
 '(isearch-fail ((((class color) (min-colors 16777215)) (:background "#fb4933" :foreground "#fdf4c1")) (((class color) (min-colors 255)) (:background "#d75f5f" :foreground "#ffffaf"))))
 '(lazy-highlight ((((class color) (min-colors 16777215)) (:background "#fabd2f" :foreground "#000000")) (((class color) (min-colors 255)) (:background "#ffaf00" :foreground "#000000"))))
 '(match ((((class color) (min-colors 16777215)) (:background "#83a598" :foreground "#282828")) (((class color) (min-colors 255)) (:background "#87afaf" :foreground "#262626"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'hrbsd)
